version: '3.4'

services:
  infra-mongo:
    extends:
      file: ./base.yml
      service: nx
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    command: nx test infra-mongo --watchAll
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
