version: '3.4'

services:
  api:
    extends:
      file: ./base.yml
      service: nx
    ports:
      - 8080:8080
    environment:
      - EXPRESS_HOST=0.0.0.0
      - EXPRESS_PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: nx serve api --configuration=development
    depends_on:
      - redis
  newsletter:
    extends:
      file: ./base.yml
      service: nx
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: nx serve newsletter --configuration=development
    depends_on:
      - redis
  ui:
    extends:
      file: ./base.yml
      service: nx
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: nx serve ui --configuration=development
    depends_on:
      - redis
  redis:
    image: 'redis:alpine'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
